---
title: Population structure
output:
  html_document: default
---

In this script we will estimate the genetic distance between populations on the HGDP and 1000G reference samples.
The merging of those databases can be found [here](http://tomszar.github.io/HGDP_1000G_Merge).

## Preliminaries

Load packages

```{r packages, message=FALSE}
library(tidyverse)
library(adegenet)
library(data.table)
library(ape)
```

Load databases

```{r databases, message=FALSE, warning=FALSE}
setwd('..')
path <- getwd()
setwd(paste(path, "/Results/Counts", sep = ""))
allelecounts <- fread("CleanGenos_strict_wide.frq.strat", sep = ",", header = TRUE, 
                      data.table = FALSE, index = "Pop")
rownames(allelecounts) <- allelecounts$Pop
allelecounts           <- allelecounts[,-c(1,2)]

setwd(paste(path, "/DataBases/PopInfo", sep = ""))
pops_hgdp <- read_delim("SampleInformation.txt", delim = "\t")[,c(3,5)]
colnames(pops_hgdp) <- c("pop", "super_pop")
pops_100g <- read_delim("integrated_call_samples_v3.20130502.ALL.panel", delim = "\t")[,c(2,3)]
#Getting pop - super_pop relation
pops <- rbind(unique(pops_100g), unique(pops_hgdp))
pops <- pops[pops$pop %in% rownames(allelecounts),]
#Changing super_pop names
pops$super_pop[pops$super_pop == "AFRICA"]      <- "AFR"
pops$super_pop[pops$super_pop == "AMERICA"]     <- "AMR"
pops$super_pop[pops$super_pop == "EAST_ASIA"]   <- "EAS"
pops$super_pop[pops$super_pop == "EUROPE"]      <- "EUR"
pops$super_pop[pops$super_pop == "MIDDLE_EAST"] <- "MDE"
pops$super_pop[pops$super_pop == "OCEANIA"]     <- "OCE"
pops$super_pop[pops$super_pop == "CENTRAL_SOUTH_ASIA"] <- "SAS"

#counts to genpop
mygenpop <- genpop(allelecounts, ploidy=as.integer(2), type="codom")

#color palette
okabeito <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

## Distance estimation

Estimating Nei's distance

```{r dendogram, fig.height=6, fig.width=12}
#Getting Nei's distance
neidist <- dist.genpop(mygenpop)
#Getting reynold's distance
reydist <- dist.genpop(mygenpop, method = 3)
```

Plot dendrograms

```{r}
labs <- as.data.frame(hclust(neidist)$labels)
colnames(labs) <- "pop"
labs <- merge(labs, pops, by = "pop", sort = FALSE)
labs$super_pop <- as.factor(labs$super_pop)
levels(labs$super_pop) <- okabeito

#Plot
plot(as.phylo(hclust(neidist)), type = "fan", tip.color = as.character(labs$super_pop))
plot(as.phylo(hclust(reydist)), type = "fan", tip.color = as.character(labs$super_pop))
```

Saving dist object

```{r saving, message=FALSE}
setwd(paste(path, "/Results/Distances", sep = ""))
write.csv(as.matrix(neidist), file = "Nei_dist.csv", quote = FALSE)
```

